dependencies:
  - python=3
  - conda
  - pip
  - pip:
    - numpy
    - scikit-learn
    - matplotlib
    - pillow
    - opencv-python
    - tensorflow
    - ipywidgets
    - jupyter_drawing_pad
